[31m[31merror[31m[39m:   uncaughtException: listen EADDRINUSE: address already in use :::4000
Error: listen EADDRINUSE: address already in use :::4000
    at Server.setupListenHandle [as _listen2] (net.js:1309:16)
    at listenInCluster (net.js:1357:12)
    at Server.listen (net.js:1445:7)
    at Function.listen (/home/natalie/node-course/nodejs-course/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/home/natalie/node-course/nodejs-course/src/server.js:4:5)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
[31m[31merror[31m[39m:   uncaughtException: listen EADDRINUSE: address already in use :::4000
Error: listen EADDRINUSE: address already in use :::4000
    at Server.setupListenHandle [as _listen2] (net.js:1309:16)
    at listenInCluster (net.js:1357:12)
    at Server.listen (net.js:1445:7)
    at Function.listen (/home/natalie/node-course/nodejs-course/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/home/natalie/node-course/nodejs-course/src/server.js:13:5)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
[31m[31merror[31m[39m:   uncaughtException: listen EADDRINUSE: address already in use :::4000
Error: listen EADDRINUSE: address already in use :::4000
    at Server.setupListenHandle [as _listen2] (net.js:1309:16)
    at listenInCluster (net.js:1357:12)
    at Server.listen (net.js:1445:7)
    at Function.listen (/home/natalie/node-course/nodejs-course/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/home/natalie/node-course/nodejs-course/src/server.js:13:5)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
[31m[31merror[31m[39m:   uncaughtException: listen EADDRINUSE: address already in use :::4000
Error: listen EADDRINUSE: address already in use :::4000
    at Server.setupListenHandle [as _listen2] (net.js:1309:16)
    at listenInCluster (net.js:1357:12)
    at Server.listen (net.js:1445:7)
    at Function.listen (/home/natalie/node-course/nodejs-course/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/home/natalie/node-course/nodejs-course/src/server.js:13:5)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
[31m[31merror[31m[39m:   uncaughtException: listen EADDRINUSE: address already in use :::4000
Error: listen EADDRINUSE: address already in use :::4000
    at Server.setupListenHandle [as _listen2] (net.js:1309:16)
    at listenInCluster (net.js:1357:12)
    at Server.listen (net.js:1445:7)
    at Function.listen (/home/natalie/node-course/nodejs-course/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/home/natalie/node-course/nodejs-course/src/server.js:13:5)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
[31m[31merror[31m[39m:   uncaughtException: listen EADDRINUSE: address already in use :::4000
Error: listen EADDRINUSE: address already in use :::4000
    at Server.setupListenHandle [as _listen2] (net.js:1309:16)
    at listenInCluster (net.js:1357:12)
    at Server.listen (net.js:1445:7)
    at Function.listen (/home/natalie/node-course/nodejs-course/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/home/natalie/node-course/nodejs-course/src/server.js:13:5)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
[31m[31merror[31m[39m:   uncaughtException: listen EADDRINUSE: address already in use :::4000
Error: listen EADDRINUSE: address already in use :::4000
    at Server.setupListenHandle [as _listen2] (net.js:1309:16)
    at listenInCluster (net.js:1357:12)
    at Server.listen (net.js:1445:7)
    at Function.listen (/home/natalie/node-course/nodejs-course/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/home/natalie/node-course/nodejs-course/src/server.js:13:5)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
[31m[31merror[31m[39m:   uncaughtException: listen EADDRINUSE: address already in use :::4000
Error: listen EADDRINUSE: address already in use :::4000
    at Server.setupListenHandle [as _listen2] (net.js:1309:16)
    at listenInCluster (net.js:1357:12)
    at Server.listen (net.js:1445:7)
    at Function.listen (/home/natalie/node-course/nodejs-course/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/home/natalie/node-course/nodejs-course/src/server.js:13:5)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
[31m[31merror[31m[39m:   uncaughtException: listen EADDRINUSE: address already in use :::4000
Error: listen EADDRINUSE: address already in use :::4000
    at Server.setupListenHandle [as _listen2] (net.js:1309:16)
    at listenInCluster (net.js:1357:12)
    at Server.listen (net.js:1445:7)
    at Function.listen (/home/natalie/node-course/nodejs-course/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/home/natalie/node-course/nodejs-course/src/server.js:13:5)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
[31m[31merror[31m[39m:   uncaughtException: listen EADDRINUSE: address already in use :::4000
Error: listen EADDRINUSE: address already in use :::4000
    at Server.setupListenHandle [as _listen2] (net.js:1309:16)
    at listenInCluster (net.js:1357:12)
    at Server.listen (net.js:1445:7)
    at Function.listen (/home/natalie/node-course/nodejs-course/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/home/natalie/node-course/nodejs-course/src/server.js:13:5)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
[31m[31merror[31m[39m:   uncaughtException: listen EADDRINUSE: address already in use :::4000
Error: listen EADDRINUSE: address already in use :::4000
    at Server.setupListenHandle [as _listen2] (net.js:1309:16)
    at listenInCluster (net.js:1357:12)
    at Server.listen (net.js:1445:7)
    at Function.listen (/home/natalie/node-course/nodejs-course/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/home/natalie/node-course/nodejs-course/src/server.js:13:5)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
[31m[31merror[31m[39m:   uncaughtException: listen EADDRINUSE: address already in use :::4000
Error: listen EADDRINUSE: address already in use :::4000
    at Server.setupListenHandle [as _listen2] (net.js:1309:16)
    at listenInCluster (net.js:1357:12)
    at Server.listen (net.js:1445:7)
    at Function.listen (/home/natalie/node-course/nodejs-course/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/home/natalie/node-course/nodejs-course/src/server.js:13:5)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
[31m[31merror[31m[39m:   uncaughtException: Oops!
Error: Oops!
    at Object.<anonymous> (/home/natalie/node-course/nodejs-course/src/app.js:53:7)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/natalie/node-course/nodejs-course/src/server.js:2:13)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
[31m[31merror[31m[39m:   uncaughtException: listen EADDRINUSE: address already in use :::4000
Error: listen EADDRINUSE: address already in use :::4000
    at Server.setupListenHandle [as _listen2] (net.js:1309:16)
    at listenInCluster (net.js:1357:12)
    at Server.listen (net.js:1445:7)
    at Function.listen (/home/natalie/node-course/nodejs-course/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/home/natalie/node-course/nodejs-course/src/server.js:13:5)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
[31m[31merror[31m[39m:   uncaughtException: listen EADDRINUSE: address already in use :::4000
Error: listen EADDRINUSE: address already in use :::4000
    at Server.setupListenHandle [as _listen2] (net.js:1309:16)
    at listenInCluster (net.js:1357:12)
    at Server.listen (net.js:1445:7)
    at Function.listen (/home/natalie/node-course/nodejs-course/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/home/natalie/node-course/nodejs-course/src/server.js:15:5)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
[31m[31merror[31m[39m:   uncaughtException: listen EADDRINUSE: address already in use :::4000
Error: listen EADDRINUSE: address already in use :::4000
    at Server.setupListenHandle [as _listen2] (net.js:1309:16)
    at listenInCluster (net.js:1357:12)
    at Server.listen (net.js:1445:7)
    at Function.listen (/home/natalie/node-course/nodejs-course/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/home/natalie/node-course/nodejs-course/src/server.js:15:5)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
[31m[31merror[31m[39m:   uncaughtException: listen EADDRINUSE: address already in use :::4000
Error: listen EADDRINUSE: address already in use :::4000
    at Server.setupListenHandle [as _listen2] (net.js:1309:16)
    at listenInCluster (net.js:1357:12)
    at Server.listen (net.js:1445:7)
    at Function.listen (/home/natalie/node-course/nodejs-course/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/home/natalie/node-course/nodejs-course/src/server.js:15:5)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
[31m[31merror[31m[39m:   uncaughtException: listen EADDRINUSE: address already in use :::4000
Error: listen EADDRINUSE: address already in use :::4000
    at Server.setupListenHandle [as _listen2] (net.js:1309:16)
    at listenInCluster (net.js:1357:12)
    at Server.listen (net.js:1445:7)
    at Function.listen (/home/natalie/node-course/nodejs-course/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/home/natalie/node-course/nodejs-course/src/server.js:15:5)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
[31m[31merror[31m[39m:   uncaughtException: listen EADDRINUSE: address already in use :::4000
Error: listen EADDRINUSE: address already in use :::4000
    at Server.setupListenHandle [as _listen2] (net.js:1309:16)
    at listenInCluster (net.js:1357:12)
    at Server.listen (net.js:1445:7)
    at Function.listen (/home/natalie/node-course/nodejs-course/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/home/natalie/node-course/nodejs-course/src/server.js:15:5)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
[31m[31merror[31m[39m:   uncaughtException: listen EADDRINUSE: address already in use :::4000
Error: listen EADDRINUSE: address already in use :::4000
    at Server.setupListenHandle [as _listen2] (net.js:1309:16)
    at listenInCluster (net.js:1357:12)
    at Server.listen (net.js:1445:7)
    at Function.listen (/home/natalie/node-course/nodejs-course/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/home/natalie/node-course/nodejs-course/src/server.js:15:5)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
[31m[31merror[31m[39m:   uncaughtException: listen EADDRINUSE: address already in use :::4000
Error: listen EADDRINUSE: address already in use :::4000
    at Server.setupListenHandle [as _listen2] (net.js:1309:16)
    at listenInCluster (net.js:1357:12)
    at Server.listen (net.js:1445:7)
    at Function.listen (/home/natalie/node-course/nodejs-course/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/home/natalie/node-course/nodejs-course/src/server.js:15:5)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
[31m[31merror[31m[39m:   uncaughtException: User is not defined
ReferenceError: User is not defined
    at Object.<anonymous> (/home/natalie/node-course/nodejs-course/src/db/db.client.js:6:7)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/natalie/node-course/nodejs-course/src/server.js:3:24)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
[31m[31merror[31m[39m:   uncaughtException: user.save is not a function
TypeError: user.save is not a function
    at /home/natalie/node-course/nodejs-course/src/db/db.client.js:22:32
    at Array.forEach (<anonymous>)
    at NativeConnection.<anonymous> (/home/natalie/node-course/nodejs-course/src/db/db.client.js:22:11)
    at Object.onceWrapper (events.js:417:28)
    at NativeConnection.emit (events.js:311:20)
    at /home/natalie/node-course/nodejs-course/node_modules/mongoose/lib/connection.js:819:13
    at /home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/utils.js:731:5
    at /home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/mongo_client.js:217:7
    at connectCallback (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/operations/connect.js:350:5)
    at /home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/operations/connect.js:586:5
    at Object.callback (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/core/sdam/topology.js:297:43)
    at processWaitQueue (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/core/sdam/topology.js:1036:21)
    at NativeTopology.serverUpdateHandler (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/core/sdam/topology.js:554:7)
    at Server.emit (events.js:311:20)
    at Monitor.<anonymous> (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/core/sdam/server.js:147:12)
    at Monitor.emit (events.js:323:22)
[31m[31merror[31m[39m:   uncaughtException: user.save is not a function
TypeError: user.save is not a function
    at /home/natalie/node-course/nodejs-course/src/db/db.client.js:22:32
    at Array.forEach (<anonymous>)
    at NativeConnection.<anonymous> (/home/natalie/node-course/nodejs-course/src/db/db.client.js:22:11)
    at Object.onceWrapper (events.js:417:28)
    at NativeConnection.emit (events.js:311:20)
    at /home/natalie/node-course/nodejs-course/node_modules/mongoose/lib/connection.js:819:13
    at /home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/utils.js:731:5
    at /home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/mongo_client.js:217:7
    at connectCallback (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/operations/connect.js:350:5)
    at /home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/operations/connect.js:586:5
    at Object.callback (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/core/sdam/topology.js:297:43)
    at processWaitQueue (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/core/sdam/topology.js:1036:21)
    at NativeTopology.serverUpdateHandler (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/core/sdam/topology.js:554:7)
    at Server.emit (events.js:311:20)
    at Monitor.<anonymous> (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/core/sdam/server.js:147:12)
    at Monitor.emit (events.js:323:22)
[31m[31merror[31m[39m:   uncaughtException: user.save is not a function
TypeError: user.save is not a function
    at /home/natalie/node-course/nodejs-course/src/db/db.client.js:24:32
    at Array.forEach (<anonymous>)
    at NativeConnection.<anonymous> (/home/natalie/node-course/nodejs-course/src/db/db.client.js:24:11)
    at Object.onceWrapper (events.js:417:28)
    at NativeConnection.emit (events.js:311:20)
    at /home/natalie/node-course/nodejs-course/node_modules/mongoose/lib/connection.js:819:13
    at /home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/utils.js:731:5
    at /home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/mongo_client.js:217:7
    at connectCallback (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/operations/connect.js:350:5)
    at /home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/operations/connect.js:586:5
    at Object.callback (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/core/sdam/topology.js:297:43)
    at processWaitQueue (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/core/sdam/topology.js:1036:21)
    at NativeTopology.serverUpdateHandler (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/core/sdam/topology.js:554:7)
    at Server.emit (events.js:311:20)
    at Monitor.<anonymous> (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/core/sdam/server.js:147:12)
    at Monitor.emit (events.js:323:22)
[31m[31merror[31m[39m:   uncaughtException: listen EADDRINUSE: address already in use :::4000
Error: listen EADDRINUSE: address already in use :::4000
    at Server.setupListenHandle [as _listen2] (net.js:1309:16)
    at listenInCluster (net.js:1357:12)
    at Server.listen (net.js:1445:7)
    at Function.listen (/home/natalie/node-course/nodejs-course/node_modules/express/lib/application.js:618:24)
    at /home/natalie/node-course/nodejs-course/src/server.js:15:7
    at NativeConnection.<anonymous> (/home/natalie/node-course/nodejs-course/src/db/db.client.js:49:5)
    at Object.onceWrapper (events.js:417:28)
    at NativeConnection.emit (events.js:311:20)
    at /home/natalie/node-course/nodejs-course/node_modules/mongoose/lib/connection.js:819:13
    at /home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/utils.js:731:5
    at /home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/mongo_client.js:217:7
    at connectCallback (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/operations/connect.js:350:5)
    at /home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/operations/connect.js:586:5
    at Object.callback (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/core/sdam/topology.js:297:43)
    at processWaitQueue (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/core/sdam/topology.js:1036:21)
    at NativeTopology.serverUpdateHandler (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/core/sdam/topology.js:554:7)
[31m[31merror[31m[39m:   uncaughtException: listen EADDRINUSE: address already in use :::4000
Error: listen EADDRINUSE: address already in use :::4000
    at Server.setupListenHandle [as _listen2] (net.js:1309:16)
    at listenInCluster (net.js:1357:12)
    at Server.listen (net.js:1445:7)
    at Function.listen (/home/natalie/node-course/nodejs-course/node_modules/express/lib/application.js:618:24)
    at /home/natalie/node-course/nodejs-course/src/server.js:15:7
    at NativeConnection.<anonymous> (/home/natalie/node-course/nodejs-course/src/db/db.client.js:49:5)
    at Object.onceWrapper (events.js:417:28)
    at NativeConnection.emit (events.js:311:20)
    at /home/natalie/node-course/nodejs-course/node_modules/mongoose/lib/connection.js:819:13
    at /home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/utils.js:731:5
    at /home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/mongo_client.js:217:7
    at connectCallback (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/operations/connect.js:350:5)
    at /home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/operations/connect.js:586:5
    at Object.callback (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/core/sdam/topology.js:297:43)
    at processWaitQueue (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/core/sdam/topology.js:1036:21)
    at NativeTopology.serverUpdateHandler (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/core/sdam/topology.js:554:7)
[31m[31merror[31m[39m:   uncaughtException: listen EADDRINUSE: address already in use :::4000
Error: listen EADDRINUSE: address already in use :::4000
    at Server.setupListenHandle [as _listen2] (net.js:1309:16)
    at listenInCluster (net.js:1357:12)
    at Server.listen (net.js:1445:7)
    at Function.listen (/home/natalie/node-course/nodejs-course/node_modules/express/lib/application.js:618:24)
    at /home/natalie/node-course/nodejs-course/src/server.js:15:7
    at NativeConnection.<anonymous> (/home/natalie/node-course/nodejs-course/src/db/db.client.js:49:5)
    at Object.onceWrapper (events.js:417:28)
    at NativeConnection.emit (events.js:311:20)
    at /home/natalie/node-course/nodejs-course/node_modules/mongoose/lib/connection.js:819:13
    at /home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/utils.js:731:5
    at /home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/mongo_client.js:217:7
    at connectCallback (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/operations/connect.js:350:5)
    at /home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/operations/connect.js:586:5
    at Object.callback (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/core/sdam/topology.js:297:43)
    at processWaitQueue (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/core/sdam/topology.js:1036:21)
    at NativeTopology.serverUpdateHandler (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/core/sdam/topology.js:554:7)
[31m[31merror[31m[39m:   uncaughtException: listen EADDRINUSE: address already in use :::4000
Error: listen EADDRINUSE: address already in use :::4000
    at Server.setupListenHandle [as _listen2] (net.js:1309:16)
    at listenInCluster (net.js:1357:12)
    at Server.listen (net.js:1445:7)
    at Function.listen (/home/natalie/node-course/nodejs-course/node_modules/express/lib/application.js:618:24)
    at /home/natalie/node-course/nodejs-course/src/server.js:15:7
    at NativeConnection.<anonymous> (/home/natalie/node-course/nodejs-course/src/db/db.client.js:49:5)
    at Object.onceWrapper (events.js:417:28)
    at NativeConnection.emit (events.js:311:20)
    at /home/natalie/node-course/nodejs-course/node_modules/mongoose/lib/connection.js:819:13
    at /home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/utils.js:731:5
    at /home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/mongo_client.js:217:7
    at connectCallback (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/operations/connect.js:350:5)
    at /home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/operations/connect.js:586:5
    at Object.callback (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/core/sdam/topology.js:297:43)
    at processWaitQueue (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/core/sdam/topology.js:1036:21)
    at NativeTopology.serverUpdateHandler (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/core/sdam/topology.js:554:7)
[31m[31merror[31m[39m:   uncaughtException: Unexpected token '}'
/home/natalie/node-course/nodejs-course/src/resources/boards/board.db.repository.js:15
};
^

SyntaxError: Unexpected token '}'
    at wrapSafe (internal/modules/cjs/loader.js:1072:16)
    at Module._compile (internal/modules/cjs/loader.js:1122:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/natalie/node-course/nodejs-course/src/resources/boards/board.service.js:2:20)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/natalie/node-course/nodejs-course/src/resources/boards/board.router.js:2:23)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
[31m[31merror[31m[39m:   uncaughtException: Unexpected token '}'
/home/natalie/node-course/nodejs-course/src/resources/boards/board.db.repository.js:15
};
^

SyntaxError: Unexpected token '}'
    at wrapSafe (internal/modules/cjs/loader.js:1072:16)
    at Module._compile (internal/modules/cjs/loader.js:1122:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/natalie/node-course/nodejs-course/src/resources/boards/board.service.js:2:20)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/natalie/node-course/nodejs-course/src/resources/boards/board.router.js:2:23)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
[31m[31merror[31m[39m:   uncaughtException: Unexpected token 'return'
/home/natalie/node-course/nodejs-course/src/resources/boards/board.db.repository.js:9
const getAll = async () => return Board.find({});
                           ^^^^^^

SyntaxError: Unexpected token 'return'
    at wrapSafe (internal/modules/cjs/loader.js:1072:16)
    at Module._compile (internal/modules/cjs/loader.js:1122:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/natalie/node-course/nodejs-course/src/resources/boards/board.service.js:2:20)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/natalie/node-course/nodejs-course/src/resources/boards/board.router.js:2:23)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
[31m[31merror[31m[39m:   uncaughtException: Unexpected token 'return'
/home/natalie/node-course/nodejs-course/src/resources/boards/board.db.repository.js:11
const getBoard = async id => return Board.findById(id);
                             ^^^^^^

SyntaxError: Unexpected token 'return'
    at wrapSafe (internal/modules/cjs/loader.js:1072:16)
    at Module._compile (internal/modules/cjs/loader.js:1122:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/natalie/node-course/nodejs-course/src/resources/boards/board.service.js:2:20)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/natalie/node-course/nodejs-course/src/resources/boards/board.router.js:2:23)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
[31m[31merror[31m[39m:   uncaughtException: listen EADDRINUSE: address already in use :::4000
Error: listen EADDRINUSE: address already in use :::4000
    at Server.setupListenHandle [as _listen2] (net.js:1309:16)
    at listenInCluster (net.js:1357:12)
    at Server.listen (net.js:1445:7)
    at Function.listen (/home/natalie/node-course/nodejs-course/node_modules/express/lib/application.js:618:24)
    at /home/natalie/node-course/nodejs-course/src/server.js:15:7
    at NativeConnection.<anonymous> (/home/natalie/node-course/nodejs-course/src/db/db.client.js:50:5)
    at Object.onceWrapper (events.js:417:28)
    at NativeConnection.emit (events.js:311:20)
    at /home/natalie/node-course/nodejs-course/node_modules/mongoose/lib/connection.js:819:13
    at /home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/utils.js:731:5
    at /home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/mongo_client.js:217:7
    at connectCallback (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/operations/connect.js:350:5)
    at /home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/operations/connect.js:586:5
    at Object.callback (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/core/sdam/topology.js:297:43)
    at processWaitQueue (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/core/sdam/topology.js:1036:21)
    at NativeTopology.serverUpdateHandler (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/core/sdam/topology.js:554:7)
[31m[31merror[31m[39m:   uncaughtException: listen EADDRINUSE: address already in use :::4000
Error: listen EADDRINUSE: address already in use :::4000
    at Server.setupListenHandle [as _listen2] (net.js:1309:16)
    at listenInCluster (net.js:1357:12)
    at Server.listen (net.js:1445:7)
    at Function.listen (/home/natalie/node-course/nodejs-course/node_modules/express/lib/application.js:618:24)
    at /home/natalie/node-course/nodejs-course/src/server.js:15:7
    at NativeConnection.<anonymous> (/home/natalie/node-course/nodejs-course/src/db/db.client.js:51:5)
    at Object.onceWrapper (events.js:417:28)
    at NativeConnection.emit (events.js:311:20)
    at /home/natalie/node-course/nodejs-course/node_modules/mongoose/lib/connection.js:819:13
    at /home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/utils.js:731:5
    at /home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/mongo_client.js:217:7
    at connectCallback (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/operations/connect.js:350:5)
    at /home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/operations/connect.js:586:5
    at Object.callback (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/core/sdam/topology.js:297:43)
    at processWaitQueue (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/core/sdam/topology.js:1036:21)
    at NativeTopology.serverUpdateHandler (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/core/sdam/topology.js:554:7)
[31m[31merror[31m[39m:   uncaughtException: listen EADDRINUSE: address already in use :::4000
Error: listen EADDRINUSE: address already in use :::4000
    at Server.setupListenHandle [as _listen2] (net.js:1309:16)
    at listenInCluster (net.js:1357:12)
    at Server.listen (net.js:1445:7)
    at Function.listen (/home/natalie/node-course/nodejs-course/node_modules/express/lib/application.js:618:24)
    at /home/natalie/node-course/nodejs-course/src/server.js:15:7
    at NativeConnection.<anonymous> (/home/natalie/node-course/nodejs-course/src/db/db.client.js:51:5)
    at Object.onceWrapper (events.js:417:28)
    at NativeConnection.emit (events.js:311:20)
    at /home/natalie/node-course/nodejs-course/node_modules/mongoose/lib/connection.js:819:13
    at /home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/utils.js:731:5
    at /home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/mongo_client.js:217:7
    at connectCallback (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/operations/connect.js:350:5)
    at /home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/operations/connect.js:586:5
    at Object.callback (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/core/sdam/topology.js:297:43)
    at processWaitQueue (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/core/sdam/topology.js:1036:21)
    at NativeTopology.serverUpdateHandler (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/core/sdam/topology.js:554:7)
[31m[31merror[31m[39m:   uncaughtException: listen EADDRINUSE: address already in use :::4000
Error: listen EADDRINUSE: address already in use :::4000
    at Server.setupListenHandle [as _listen2] (net.js:1309:16)
    at listenInCluster (net.js:1357:12)
    at Server.listen (net.js:1445:7)
    at Function.listen (/home/natalie/node-course/nodejs-course/node_modules/express/lib/application.js:618:24)
    at /home/natalie/node-course/nodejs-course/src/server.js:15:7
    at NativeConnection.<anonymous> (/home/natalie/node-course/nodejs-course/src/db/db.client.js:51:5)
    at Object.onceWrapper (events.js:417:28)
    at NativeConnection.emit (events.js:311:20)
    at /home/natalie/node-course/nodejs-course/node_modules/mongoose/lib/connection.js:819:13
    at /home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/utils.js:731:5
    at /home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/mongo_client.js:217:7
    at connectCallback (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/operations/connect.js:350:5)
    at /home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/operations/connect.js:586:5
    at Object.callback (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/core/sdam/topology.js:297:43)
    at processWaitQueue (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/core/sdam/topology.js:1036:21)
    at NativeTopology.serverUpdateHandler (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/core/sdam/topology.js:554:7)
[31m[31merror[31m[39m:   uncaughtException: listen EADDRINUSE: address already in use :::4000
Error: listen EADDRINUSE: address already in use :::4000
    at Server.setupListenHandle [as _listen2] (net.js:1309:16)
    at listenInCluster (net.js:1357:12)
    at Server.listen (net.js:1445:7)
    at Function.listen (/home/natalie/node-course/nodejs-course/node_modules/express/lib/application.js:618:24)
    at /home/natalie/node-course/nodejs-course/src/server.js:15:7
    at NativeConnection.<anonymous> (/home/natalie/node-course/nodejs-course/src/db/db.client.js:51:5)
    at Object.onceWrapper (events.js:417:28)
    at NativeConnection.emit (events.js:311:20)
    at /home/natalie/node-course/nodejs-course/node_modules/mongoose/lib/connection.js:819:13
    at /home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/utils.js:731:5
    at /home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/mongo_client.js:217:7
    at connectCallback (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/operations/connect.js:350:5)
    at /home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/operations/connect.js:586:5
    at Object.callback (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/core/sdam/topology.js:297:43)
    at processWaitQueue (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/core/sdam/topology.js:1036:21)
    at NativeTopology.serverUpdateHandler (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/core/sdam/topology.js:554:7)
[31m[31merror[31m[39m:   uncaughtException: await is only valid in async function
/home/natalie/node-course/nodejs-course/src/resources/boards/board.db.repository.js:22
  const updated = await Board.findByIdAndUpdate(
                  ^^^^^

SyntaxError: await is only valid in async function
    at wrapSafe (internal/modules/cjs/loader.js:1072:16)
    at Module._compile (internal/modules/cjs/loader.js:1122:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/natalie/node-course/nodejs-course/src/resources/boards/board.service.js:2:20)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/natalie/node-course/nodejs-course/src/resources/boards/board.router.js:2:23)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
[31m[31merror[31m[39m:   uncaughtException: await is only valid in async function
/home/natalie/node-course/nodejs-course/src/resources/boards/board.db.repository.js:22
  const updated = await Board.findByIdAndUpdate(
                  ^^^^^

SyntaxError: await is only valid in async function
    at wrapSafe (internal/modules/cjs/loader.js:1072:16)
    at Module._compile (internal/modules/cjs/loader.js:1122:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/natalie/node-course/nodejs-course/src/resources/boards/board.service.js:2:20)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/natalie/node-course/nodejs-course/src/resources/boards/board.router.js:2:23)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
[31m[31merror[31m[39m:   uncaughtException: await is only valid in async function
/home/natalie/node-course/nodejs-course/src/resources/boards/board.db.repository.js:22
  const updated = await Board.findByIdAndUpdate(
                  ^^^^^

SyntaxError: await is only valid in async function
    at wrapSafe (internal/modules/cjs/loader.js:1072:16)
    at Module._compile (internal/modules/cjs/loader.js:1122:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/natalie/node-course/nodejs-course/src/resources/boards/board.service.js:2:20)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/natalie/node-course/nodejs-course/src/resources/boards/board.router.js:2:23)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
[31m[31merror[31m[39m:   uncaughtException: await is only valid in async function
/home/natalie/node-course/nodejs-course/src/resources/boards/board.db.repository.js:22
  const updated = await Board.findByIdAndUpdate(
                  ^^^^^

SyntaxError: await is only valid in async function
    at wrapSafe (internal/modules/cjs/loader.js:1072:16)
    at Module._compile (internal/modules/cjs/loader.js:1122:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/natalie/node-course/nodejs-course/src/resources/boards/board.service.js:2:20)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/natalie/node-course/nodejs-course/src/resources/boards/board.router.js:2:23)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
[31m[31merror[31m[39m:   uncaughtException: await is only valid in async function
/home/natalie/node-course/nodejs-course/src/resources/boards/board.db.repository.js:22
  const updated = await Board.findByIdAndUpdate(
                  ^^^^^

SyntaxError: await is only valid in async function
    at wrapSafe (internal/modules/cjs/loader.js:1072:16)
    at Module._compile (internal/modules/cjs/loader.js:1122:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/natalie/node-course/nodejs-course/src/resources/boards/board.service.js:2:20)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/natalie/node-course/nodejs-course/src/resources/boards/board.router.js:2:23)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
[31m[31merror[31m[39m:   uncaughtException: Unexpected token ')'
/home/natalie/node-course/nodejs-course/src/resources/boards/board.db.repository.js:27
  console.log(delete)
                    ^

SyntaxError: Unexpected token ')'
    at wrapSafe (internal/modules/cjs/loader.js:1072:16)
    at Module._compile (internal/modules/cjs/loader.js:1122:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/natalie/node-course/nodejs-course/src/resources/boards/board.service.js:2:20)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/natalie/node-course/nodejs-course/src/resources/boards/board.router.js:2:23)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
[31m[31merror[31m[39m:   uncaughtException: missing ) after argument list
/home/natalie/node-course/nodejs-course/src/resources/tasks/task.db.repository.js:30
    console.log(task 'getallrasks')
                ^^^^

SyntaxError: missing ) after argument list
    at wrapSafe (internal/modules/cjs/loader.js:1072:16)
    at Module._compile (internal/modules/cjs/loader.js:1122:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/natalie/node-course/nodejs-course/src/resources/tasks/task.service.js:1:19)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/natalie/node-course/nodejs-course/src/resources/tasks/task.router.js:2:22)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
[31m[31merror[31m[39m:   uncaughtException: await is only valid in async function
/home/natalie/node-course/nodejs-course/src/resources/tasks/task.db.repository.js:45
  const isValidateBoard = await boardsService.getBoard(boardId);
                          ^^^^^

SyntaxError: await is only valid in async function
    at wrapSafe (internal/modules/cjs/loader.js:1072:16)
    at Module._compile (internal/modules/cjs/loader.js:1122:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/natalie/node-course/nodejs-course/src/resources/tasks/task.service.js:1:19)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/natalie/node-course/nodejs-course/src/resources/tasks/task.router.js:2:22)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
[31m[31merror[31m[39m:   uncaughtException: await is only valid in async function
/home/natalie/node-course/nodejs-course/src/resources/tasks/task.db.repository.js:45
  const isValidateBoard = await boardsService.getBoard(boardId);
                          ^^^^^

SyntaxError: await is only valid in async function
    at wrapSafe (internal/modules/cjs/loader.js:1072:16)
    at Module._compile (internal/modules/cjs/loader.js:1122:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/natalie/node-course/nodejs-course/src/resources/tasks/task.service.js:1:19)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/natalie/node-course/nodejs-course/src/resources/tasks/task.router.js:2:22)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
[31m[31merror[31m[39m:   uncaughtException: await is only valid in async function
/home/natalie/node-course/nodejs-course/src/resources/tasks/task.db.repository.js:45
  const isValidateBoard = await boardsService.getBoard(boardId);
                          ^^^^^

SyntaxError: await is only valid in async function
    at wrapSafe (internal/modules/cjs/loader.js:1072:16)
    at Module._compile (internal/modules/cjs/loader.js:1122:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/natalie/node-course/nodejs-course/src/resources/tasks/task.service.js:1:19)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/natalie/node-course/nodejs-course/src/resources/tasks/task.router.js:2:22)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
[31m[31merror[31m[39m:   uncaughtException: await is only valid in async function
/home/natalie/node-course/nodejs-course/src/resources/tasks/task.db.repository.js:36
  const task = await Task.findById(id);
               ^^^^^

SyntaxError: await is only valid in async function
    at wrapSafe (internal/modules/cjs/loader.js:1072:16)
    at Module._compile (internal/modules/cjs/loader.js:1122:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/natalie/node-course/nodejs-course/src/resources/tasks/task.service.js:1:19)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/natalie/node-course/nodejs-course/src/resources/tasks/task.router.js:2:22)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
[31m[31merror[31m[39m:   uncaughtException: Unexpected token ')'
/home/natalie/node-course/nodejs-course/src/resources/tasks/task.router.js:37
    console.log(updatedTask, 'updated', Task.toResponse(updatedTask)););
                                                                      ^

SyntaxError: Unexpected token ')'
    at wrapSafe (internal/modules/cjs/loader.js:1072:16)
    at Module._compile (internal/modules/cjs/loader.js:1122:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/natalie/node-course/nodejs-course/src/app.js:8:20)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/natalie/node-course/nodejs-course/src/server.js:2:13)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
[31m[31merror[31m[39m:   uncaughtException: Unexpected token ')'
/home/natalie/node-course/nodejs-course/src/resources/boards/board.router.js:62
    res.status(204).json(Board.toResponse(board)););
                                                  ^

SyntaxError: Unexpected token ')'
    at wrapSafe (internal/modules/cjs/loader.js:1072:16)
    at Module._compile (internal/modules/cjs/loader.js:1122:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/natalie/node-course/nodejs-course/src/app.js:7:21)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/natalie/node-course/nodejs-course/src/server.js:2:13)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
[31m[31merror[31m[39m:   uncaughtException: listen EADDRINUSE: address already in use :::4000
Error: listen EADDRINUSE: address already in use :::4000
    at Server.setupListenHandle [as _listen2] (net.js:1309:16)
    at listenInCluster (net.js:1357:12)
    at Server.listen (net.js:1445:7)
    at Function.listen (/home/natalie/node-course/nodejs-course/node_modules/express/lib/application.js:618:24)
    at /home/natalie/node-course/nodejs-course/src/server.js:15:7
    at NativeConnection.<anonymous> (/home/natalie/node-course/nodejs-course/src/db/db.client.js:51:5)
    at Object.onceWrapper (events.js:417:28)
    at NativeConnection.emit (events.js:311:20)
    at /home/natalie/node-course/nodejs-course/node_modules/mongoose/lib/connection.js:819:13
    at /home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/utils.js:731:5
    at /home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/mongo_client.js:217:7
    at connectCallback (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/operations/connect.js:350:5)
    at /home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/operations/connect.js:586:5
    at Object.callback (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/core/sdam/topology.js:297:43)
    at processWaitQueue (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/core/sdam/topology.js:1036:21)
    at NativeTopology.serverUpdateHandler (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/core/sdam/topology.js:554:7)
[31m[31merror[31m[39m:   uncaughtException: listen EADDRINUSE: address already in use :::4000
Error: listen EADDRINUSE: address already in use :::4000
    at Server.setupListenHandle [as _listen2] (net.js:1309:16)
    at listenInCluster (net.js:1357:12)
    at Server.listen (net.js:1445:7)
    at Function.listen (/home/natalie/node-course/nodejs-course/node_modules/express/lib/application.js:618:24)
    at /home/natalie/node-course/nodejs-course/src/server.js:15:7
    at NativeConnection.<anonymous> (/home/natalie/node-course/nodejs-course/src/db/db.client.js:51:5)
    at Object.onceWrapper (events.js:417:28)
    at NativeConnection.emit (events.js:311:20)
    at /home/natalie/node-course/nodejs-course/node_modules/mongoose/lib/connection.js:819:13
    at /home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/utils.js:731:5
    at /home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/mongo_client.js:217:7
    at connectCallback (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/operations/connect.js:350:5)
    at /home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/operations/connect.js:586:5
    at Object.callback (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/core/sdam/topology.js:297:43)
    at processWaitQueue (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/core/sdam/topology.js:1036:21)
    at NativeTopology.serverUpdateHandler (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/core/sdam/topology.js:554:7)
[31m[31merror[31m[39m:   uncaughtException: listen EADDRINUSE: address already in use :::4000
Error: listen EADDRINUSE: address already in use :::4000
    at Server.setupListenHandle [as _listen2] (net.js:1309:16)
    at listenInCluster (net.js:1357:12)
    at Server.listen (net.js:1445:7)
    at Function.listen (/home/natalie/node-course/nodejs-course/node_modules/express/lib/application.js:618:24)
    at /home/natalie/node-course/nodejs-course/src/server.js:15:7
    at NativeConnection.<anonymous> (/home/natalie/node-course/nodejs-course/src/db/db.client.js:51:5)
    at Object.onceWrapper (events.js:417:28)
    at NativeConnection.emit (events.js:311:20)
    at /home/natalie/node-course/nodejs-course/node_modules/mongoose/lib/connection.js:819:13
    at /home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/utils.js:731:5
    at /home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/mongo_client.js:217:7
    at connectCallback (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/operations/connect.js:350:5)
    at /home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/operations/connect.js:586:5
    at Object.callback (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/core/sdam/topology.js:297:43)
    at processWaitQueue (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/core/sdam/topology.js:1036:21)
    at NativeTopology.serverUpdateHandler (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/core/sdam/topology.js:554:7)
[31m[31merror[31m[39m:   uncaughtException: listen EADDRINUSE: address already in use :::4000
Error: listen EADDRINUSE: address already in use :::4000
    at Server.setupListenHandle [as _listen2] (net.js:1309:16)
    at listenInCluster (net.js:1357:12)
    at Server.listen (net.js:1445:7)
    at Function.listen (/home/natalie/node-course/nodejs-course/node_modules/express/lib/application.js:618:24)
    at /home/natalie/node-course/nodejs-course/src/server.js:15:7
    at NativeConnection.<anonymous> (/home/natalie/node-course/nodejs-course/src/db/db.client.js:51:5)
    at Object.onceWrapper (events.js:417:28)
    at NativeConnection.emit (events.js:311:20)
    at /home/natalie/node-course/nodejs-course/node_modules/mongoose/lib/connection.js:819:13
    at /home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/utils.js:731:5
    at /home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/mongo_client.js:217:7
    at connectCallback (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/operations/connect.js:350:5)
    at /home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/operations/connect.js:586:5
    at Object.callback (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/core/sdam/topology.js:297:43)
    at processWaitQueue (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/core/sdam/topology.js:1036:21)
    at NativeTopology.serverUpdateHandler (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/core/sdam/topology.js:554:7)
[31m[31merror[31m[39m:   uncaughtException: listen EADDRINUSE: address already in use :::4000
Error: listen EADDRINUSE: address already in use :::4000
    at Server.setupListenHandle [as _listen2] (net.js:1309:16)
    at listenInCluster (net.js:1357:12)
    at Server.listen (net.js:1445:7)
    at Function.listen (/home/natalie/node-course/nodejs-course/node_modules/express/lib/application.js:618:24)
    at /home/natalie/node-course/nodejs-course/src/server.js:15:7
    at NativeConnection.<anonymous> (/home/natalie/node-course/nodejs-course/src/db/db.client.js:51:5)
    at Object.onceWrapper (events.js:417:28)
    at NativeConnection.emit (events.js:311:20)
    at /home/natalie/node-course/nodejs-course/node_modules/mongoose/lib/connection.js:819:13
    at /home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/utils.js:731:5
    at /home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/mongo_client.js:217:7
    at connectCallback (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/operations/connect.js:350:5)
    at /home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/operations/connect.js:586:5
    at Object.callback (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/core/sdam/topology.js:297:43)
    at processWaitQueue (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/core/sdam/topology.js:1036:21)
    at NativeTopology.serverUpdateHandler (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/core/sdam/topology.js:554:7)
[31m[31merror[31m[39m:   uncaughtException: listen EADDRINUSE: address already in use :::4000
Error: listen EADDRINUSE: address already in use :::4000
    at Server.setupListenHandle [as _listen2] (net.js:1309:16)
    at listenInCluster (net.js:1357:12)
    at Server.listen (net.js:1445:7)
    at Function.listen (/home/natalie/node-course/nodejs-course/node_modules/express/lib/application.js:618:24)
    at /home/natalie/node-course/nodejs-course/src/server.js:15:7
    at NativeConnection.<anonymous> (/home/natalie/node-course/nodejs-course/src/db/db.client.js:51:5)
    at Object.onceWrapper (events.js:417:28)
    at NativeConnection.emit (events.js:311:20)
    at /home/natalie/node-course/nodejs-course/node_modules/mongoose/lib/connection.js:819:13
    at /home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/utils.js:731:5
    at /home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/mongo_client.js:217:7
    at connectCallback (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/operations/connect.js:350:5)
    at /home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/operations/connect.js:586:5
    at Object.callback (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/core/sdam/topology.js:297:43)
    at processWaitQueue (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/core/sdam/topology.js:1036:21)
    at NativeTopology.serverUpdateHandler (/home/natalie/node-course/nodejs-course/node_modules/mongodb/lib/core/sdam/topology.js:554:7)
